name: Deployment

on:
  push:
    branches:
      - develop

jobs:
  run_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Проверяем текущую версию Node.js
          node -v
          # Если нужно, переключаемся на нужную версию через nvm
          if command -v nvm > /dev/null; then
            nvm use 22 || nvm install 22
          fi
          # Проверяем версию ещё раз
          node -v
          # Выполняем деплой
          cd farming_dashboard_frontend_react && \
          git pull origin develop && \
          yarn && \
          yarn build && \
          sudo scp -r build/* /var/www/html/dashboard/ && \
          sudo rm -R node_modules
