name: Deployment

on:
  push:
    branches:
      - develop

jobs:
  run_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Вы можете выбрать нужную вам версию Node.js

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn

    - name: Build
      run: yarn build

    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd farming_dashboard_frontend_react && \
          git pull origin develop && \
          yarn build && \
          sudo scp -r build/* /var/www/html/dashboard/ && \
          sudo rm -R node_modules
